# Podfile para Workstation Rotation iOS

platform :ios, '14.0'
use_frameworks!

target 'iosApp' do
  # Framework compartido de Kotlin Multiplatform
  pod 'shared', :path => '../shared'
  
  # Dependencias adicionales si son necesarias
  # pod 'Alamofire', '~> 5.6'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    end
  end
end
